### REINVENT4 TOML input ###
### Staged Learning (SL) Run Mode ###

# General Options
run_type = "staged_learning"
use_cuda = true
tb_logdir = "TensorBoard_SL"
json_out_config = "SL_input.json"

[parameters]
# SL Parameters
summary_csv_prefix = "summary_SL"
use_checkpoint = false
batch_size = 128
unique_sequences = true
randomize_smiles = true

# LinkInvent Molecule Generator
prior_file = "linkinvent.prior"
agent_file = "linkinvent.prior"
smiles_file = "linkinvent_smiles.smi"

# Learning Strategy Parameters
[learning_strategy]
type = "dap"
sigma = 128
rate = 0.0001

# Diversity Filter Parameters
[diversity_filter]
type = "IdenticalMurckoScaffold"
bucket_size = 25
minscore = 0.4

# Stage Parameters (S1)
[[stage]]
chkpt_file = "SL_calc_S1.chkpt"
termination = "simple"
max_score = 1.00
min_steps = 10
max_steps = 100

# Diversity Filter Parameters (S1)
[stage.diversity_filter]
type = "IdenticalMurckoScaffold"
bucket_size = 25
minscore = 0.4

# Scoring Components (S1)
[stage.scoring]
type = "geometric_mean"
parallel = true

# DockStream: Generic docking interface with access to Glide SP
[[stage.scoring.component]]
[stage.scoring.component.DockStream]
[[stage.scoring.component.DockStream.endpoint]]
name = "ScoringComponent"
weight = 1.00
params.configuration_path = "/home/spal/REINVENT4/AutodockVina/dockerstream_config.json"
params.docker_script_path = "/home/spal/DockStream/docker.py"
params.docker_python_path = "/home/spal/miniconda3/envs/DockStream/bin/python"
transform.type = "Reverse_Sigmoid"
transform.low = -12.0
transform.high = -8.0
transform.k = 0.25

